name: VIP TOR AUTO 

on:
  schedule:
    - cron: "*/2 * * * *" # ทำงานทุก 2 นาที

jobs:
  gen-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Auto_Tor_IP_changer
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
          sudo pip3 install requests[socks]
          git clone https://github.com/FDX100/Auto_Tor_IP_changer.git
          cd Auto_Tor_IP_changer
          python3 install.py

      - name: Generate traffic
        run: |
          cd Auto_Tor_IP_changer
          aut time # Change IP address
          aut 10000 # Specify the number of times to change IP

          while true; do
            N=$(shuf -i 1-100 -n 1)
            echo "Making ${N} random requests"
            shuf -n ${N} urls.txt | envsubst | xargs -t -I {} bash -c "curl -A 'Mozilla/5.0 (Android 12; Mobile; LG-M255; rv:100.0) Gecko/100.0 Firefox/100.0Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36' {} -o /dev/null; sleep 1;" || true &
            sleep 5
          done

